### PR TITLE
Performance degradation

### PR DESCRIPTION
**Pull request by pboothe**
Find performance degradation issues on a weekly, monthly, and yearly basis.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/signal-searcher/7)

### CODE REVIEW

**Comment by fernandalavalle** [comment]
LGTM

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[degradation.py, line 71 at r2](https://reviewable.io:443/reviews/m-lab/signal-searcher/7#-KRo64zS3mDwYLGjjItA:-KRo64zS3mDwYLGjjItB:b-kab99c) ([raw file](https://github.com/m-lab/signal-searcher/blob/3db85c4d5b2edd4893ac21f1587141ca00318a36/degradation.py#L71)):*
> ```Python
>     return
>   # Recursive case
>   time_periods = time_periods[:]
> ```

why do we need this line? doesn't that simply return the same list?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/signal-searcher/7#-:-KRo8hWs1fC1P0SqOb0c:bb6ywmx)*

**Comment by fernandalavalle** [comment]
:lgtm:

sorry, the stamp is better!

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/signal-searcher/7#-:-KRo9zxlw5h6RFwJisyr:bspg3l3)*

**Comment by pboothe** [comment]
*[degradation.py, line 71 at r2](https://reviewable.io:443/reviews/m-lab/signal-searcher/7#-KRo64zS3mDwYLGjjItA:-KRoCujwqJiJ6tZGofOk:bhxptno) ([raw file](https://github.com/m-lab/signal-searcher/blob/3db85c4d5b2edd4893ac21f1587141ca00318a36/degradation.py#L71)):*
<details><summary><i>Previously, fernandalavalle wrote…</i></summary>
> why do we need this line? doesn't that simply return the same list?
</details>
It returns a copy of the list. Without this line, `time_periods.pop()` would modify the passed-in list, and would therefore affect the copy owned by the caller of this function. Accidentally modifying data structures that were passed by reference is a great way of getting bugs. All variables are passed by reference in Python (just like objects in Java).

The traditional way of solving this problem is to make sure every pop has a corresponding push, but I don't want to even have to begin to think about modifying shared-referenced variables in recursive generators. So I make a local copy, to avoid having to think about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/signal-searcher/7)*

**Comment by pboothe** [comment]
Reviewable is grumpy about the open comment, but it's clear that only Reviewable is grumpy and not Fernanda, so I am merging.

**Pull request merged**
