### PR TITLE
added severity parameter for csv

### PR DESCRIPTION
**Pull request by ruijieyew**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/signal-searcher/43)

### CODE REVIEW

**Comment by pboothe** [comment]
```$ go test ./...
# github.com/m-lab/signal-searcher/analyzer [github.com/m-lab/signal-searcher/analyzer.test]
analyzer/analyzer_test.go:30:31: too few values in composite literal
analyzer/analyzer_test.go:31:31: too few values in composite literal
analyzer/analyzer_test.go:35:31: too few values in composite literal
analyzer/analyzer_test.go:36:31: too few values in composite literal
?   	github.com/m-lab/signal-searcher	[no test files]
FAIL	github.com/m-lab/signal-searcher/analyzer [build failed]
ok  	github.com/m-lab/signal-searcher/sequencer	(cached)
FAIL
```

Looks like analyzer_test.go needs to be updated as well.

**Comment by ruijieyew** [comment]
Want to go over some calculations regarding severity when merging the array incidents ... I do not think the test case captures the possibilities well, because I am not sure how merging the array incidents should change the severity. 

Currently, I am thinking that if we want to merge two incidents and the first incident has been happening for eight months and the second incident has been happening for nine months, then the severity should be 8/17*(first_incident.severity) + 9/17*(second_incident.severity)....

**Comment by pboothe** [comment]
I am super-glad these questions are coming up here, because you are right: the answer is not obvious.  I would be worried if you thought the answers were obvious.  Your confusion (which is frustrating in the moment, I agree) means that you understand the problem and are on the right track.  Now your task is to choose the simplest possible defensible way of combining things, because you are going to have to explain it to people and you don't want that explanation to take forever.

I suggest maybe using `max`?

**Comment by pboothe** [comment]
Please merge the changes that were recently brought into master. They bring the test coverage up to 100%, which helps dispel any worries you might have about coverage.

**Pull request merged**
